name: MSBuild Reusable Workflow

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      configuration:
        required: true
        type: string
      clean:
        required: false
        default: false
        type: boolean
      maxCpu:
        required: false
        default: 4
        type: number
      msBuildArgs:
        required: false
        default: ""
        type: string

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Locate Solution File
        run: Get-ChildItem -Path ${{ github.workspace }} -Recurse -Filter "*.sln" | Select-Object -ExpandProperty FullName
        shell: pwsh

      - name: Restore NuGet Packages
        run: |
          $solution = Get-ChildItem -Path ${{ github.workspace }} -Recurse -Filter "*.sln" | Select-Object -ExpandProperty FullName
          if ($solution) { 
            Write-Host "Solution file found: $solution"
            nuget restore "$solution"
          } else { 
            Write-Host "No solution file found!" 
            exit 1 
          }
        shell: pwsh

      - name: Build Solution with MSBuild
        run: |
          msbuild "$solution" /p:Platform=${{ inputs.platform }} /p:Configuration=${{ inputs.configuration }} `
          ${{ inputs.msBuildArgs }} `
          ${{ inputs.clean && '/t:Clean' || '' }} `
          /m:${{ in
