name: MSBuild Reusable Workflow

on:
  workflow_call:
    inputs:
      solution_path:
        required: true
        type: string
      build_configuration:
        required: false
        type: string
        default: 'Release'

jobs:
  build:
    runs-on: windows-latest  # Required for MSBuild (Windows only)
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup MSBuild (Visual Studio)
        uses: microsoft/setup-msbuild@v1  # Installs MSBuild

      - name: Restore NuGet Packages
        run: nuget restore ${{ inputs.solution_path }}

      - name: Build Solution with MSBuild
        run: msbuild ${{ inputs.solution_path }} /p:Configuration=${{ inputs.build_configuration }}
